### ISSUE TITLE
adapter not enabled (ASUS BT-400)

### ISSUE THREAD

**Issue by josemariagarcia95** [thegecko/webbluetooth#14]
Hi.
I'm using the ASUS BT400 Bluetooth 4.0 adapter, and I have also installed the WinUSB driver with Zadig. I could put `noble `to work, but using this library only gets me an "adapter not enabled"

`requestDevice error: adapter not enabled`

**npm** version: v6.4.1
**node** version: v10.15.0

I'm working in **Windows 10 x64**, and I have installed **node-gyp**  and **node-bluetooth-hci-socket**. As I said, `noble `is working and detecting devices, but webbluetooth only gives me an `adapter not enabled`.

**Comment by thegecko** [comment]
Please confirm the state of the adapter for your system in a similar way to the comments here: https://github.com/thegecko/webbluetooth/issues/11

**Comment by thegecko** [comment]
Please re-open this issue with any further information
