### ISSUE TITLE
no devices found

### ISSUE THREAD

**Issue by playground** [thegecko/webbluetooth#15]
With web bluetooth api, I was able to discover devices.  But with webbluetooth & node-web-bluetooth packages, it's getting no devices found...  What am I doing wrong?

```
bluetooth.requestDevice({acceptAllDevices: true})
.then(device => {
    console.log("connecting...");
    return device.gatt.connect();
})
.then(gattServer => {
    console.log("connected");
    server = gattServer;
    return enumerateGatt(server);
})
.then(() => server.disconnect())
.then(() => {
    console.log("\ndisconnected");
    process.exit();
})
.catch(logError);
```

**Comment by thegecko** [comment]
Can you conform this device can be found using [noble](https://github.com/noble/noble)?

**Comment by playground** [comment]
I had the same issue with noble, seems like it's broken for Mojave.

**Comment by thegecko** [comment]
Oh that's not great :(
Could you raise an issue over there?

**Comment by playground** [comment]
https://github.com/noble/noble/issues/874

**Comment by c-reiter** [comment]
There should be a fix for the problems with noble on macos mojave. Just replace noble through @abandonware/noble (https://github.com/abandonware/noble). The version from abandonware should also work on windows/linux. Already replaced some other noble stuff through that and it worked perfectly.
@thegecko I tried replacing it in the webbluetooth package.json myself but then couldn't build webbluetooth, as there are some issues with node-gyp not finding some packages:
clang: error: no such file or directory: 'webbluetooth/node_modules/node-addon-api'
clang: error: no such file or directory: 'webbluetooth/node_modules/napi-thread-safe-callback'
Sadly I currently don't have time to try out fixing it myself, but if you could replace noble through @abandonware/noble, I would be glad to try if your fix works! Thanks for your amazing work on this package! :)
