### ISSUE TITLE
xpc-connection fails to install on mac

### ISSUE THREAD

**Issue by jimmywarting** [thegecko/webbluetooth#17]
do you know how install xpc-connection on mac?

**Comment by thegecko** [comment]
I use a mac to develop this package, so it should just work. Have you tried the latest release which switched to using [abandonware/noble](https://github.com/abandonware/noble)?

This fixed noble on MacOS Mojave I believe. If you still have problems with the latest release, please ensure that version of noble works on your machine.

**Comment by jimmywarting** [comment]
seems to work...
