### ISSUE TITLE
Implement getDevices()

### ISSUE THREAD

**Issue by thegecko** [thegecko/webbluetooth#26]
Web bluetooth now supports listing known devices:

https://github.com/WebBluetoothCG/web-bluetooth/pull/476

**Comment by maneetgoyal** [comment]
@thegecko Hi Rob, is this issue going to be fixed any time soon?

**Comment by thegecko** [comment]
I've made an initial pass of this, let me know if it works for you:

https://github.com/thegecko/webbluetooth/tree/get-devices

**Comment by maneetgoyal** [comment]
@thegecko Sorry for the delay.

For some reason, @abandonware/noble is not working on my system so I wasn't able to test it out.

**Comment by thegecko** [comment]
I updated this a few hours back, can you try cloning the repo and typing `yarn`?
