### ISSUE TITLE
Ubuntu 18 compatibility ? 

### ISSUE THREAD

**Issue by simonhillfr** [thegecko/webbluetooth#38]
Using webbluetooth with Node on the command line with macOS Mojave works flawlessly.

However, trying to port the same node script to Ubuntu, I manage to get a connection but I cannot subscribe to notifications, nor read data, the arrayBuffer is empty. Is this a known issue ? 

I have noticed that the node-ble library needs to set up some permissions to allow a connection with the DBus daemon, is there something similar that needs to be done to read value of a characteristic ?

**Comment by thegecko** [comment]
I honestly can't remember and no longer have a linux machine to test with :(

The noble package offers a generic API for bluetooth, so I would expect if it works on one OS, it should work on all. If not, I suspect there may be an issue (or missing bit of setup) with the noble library.

There's some linux notes here:

https://github.com/abandonware/noble#linux

I also see there's a newer version you could try? `1.9.2-15`

Failing that, it may be worth trying to get noble working natively and raising any issue there?

**Comment by simonhillfr** [comment]
Thanks, I ended up using the browser webbluetooth but it's not perfect so I'll have a look into noble
