### ISSUE TITLE
Please release new package version to npm, containing latest merged changes 

### ISSUE THREAD

**Issue by noisy** [thegecko/webbluetooth#43]
I've noticed that https://www.npmjs.com/package/webbluetooth/ was last time published over 2 years ago. A lot of people may not notice `next` version, and because of that they may think this library was not maintain for last 2 years.

Also, latest next version do not contain latest changes, like those: https://github.com/thegecko/webbluetooth/pull/42

I would greatly appreciate a new release :)

BTW, great job with this library! :) Thanks to it, I'm going to be able to write an integration of my smart-toothbrush with my smart-mirror :)

**Comment by thegecko** [comment]
Untested:

https://www.npmjs.com/package/webbluetooth/v/2.2.0

>  I'm going to be able to write an integration of my smart-toothbrush with my smart-mirror

:/

**Comment by noisy** [comment]
> https://www.npmjs.com/package/webbluetooth/v/2.2.0

great! Thanks!

**Comment by thegecko** [comment]
> I'm going to be able to write an integration of my smart-toothbrush with my smart-mirror

Video evidence required!
