### ISSUE TITLE
Allow selection of a discovered device

### ISSUE THREAD

**Issue by viktornord** [thegecko/webbluetooth#8]
Currently filter should be specified to select some bluetooth peripheral device.
Is there a way to select a certain device out of discovered ones when using this lib in node.js? It is important when I don't know beforehand which device should be connected and user interaction is needed.
For example I want to connect Mi Band 2 and there are several Mi Band 2 devices nearby but I don't know exactly which one should be connected.

**Comment by thegecko** [comment]
Please refer to the `selector` demo, specifically how the a function is injected to allow you to handle the device choosing:

https://github.com/thegecko/webbluetooth/blob/master/examples/selector.js#L63

**Comment by viktornord** [comment]
wow, sorry, didn't notice. Thanks!
