### ISSUE TITLE
I'm getting an error when writing without response

### ISSUE THREAD

**Issue by DomiR** [thegecko/webbluetooth#89]
I guess the index here is wrong? Should also use 2 like in writeWithResponse.

https://github.com/thegecko/webbluetooth/blob/7ba6cff896bcb0252ebacba4189168e77e1fb854/lib/peripheral.cpp#L398C1-L399C1

**Comment by thegecko** [comment]
Looks likely, could you open a PR?

cc @symbitic

**Comment by Symbitic** [comment]
Yeah, it looks like lines 398 and 399 should use 2 as the index.
